### récupération de toutes les listes
GET http://localhost:3000/lists

### récupération d'une liste donnée
GET http://localhost:3000/lists/1

### création d'une nouvelle liste
POST http://localhost:3000/lists
Content-Type: application/x-www-form-urlencoded

name=ma nouvelle liste
&order=1

### modification d'une liste
PATCH http://localhost:3000/lists/1
Content-Type: application/x-www-form-urlencoded

name=j'ai encore un nouveau titre
&order=5

### création d'une nouvelle liste via PUT
PUT http://localhost:3000/lists/
Content-Type: application/x-www-form-urlencoded

name=liste créer par PUT

### modification d'une liste via PUT
PUT http://localhost:3000/lists/1
Content-Type: application/x-www-form-urlencoded

name=liste modifiée par PUT

### supression d'une liste
DELETE http://localhost:3000/lists/4

### récuperer toutes les cartes d'une liste
GET http://localhost:3000/lists/1/cards

### récupérer une carte donnée
GET http://localhost:3000/cards/1

### créer une carte
POST http://localhost:3000/cards
Content-Type: application/x-www-form-urlencoded

name=une jolie carte
&list_id=1

### modifier une carte
PATCH http://localhost:3000/cards/1
Content-Type: application/x-www-form-urlencoded

name=une bien jolie carte
&color=#F0F

### modification d'une carte via PUT
PUT http://localhost:3000/cards/1
Content-Type: application/x-www-form-urlencoded

name=une tres tres jolie carte
&color=#F0F

### creation d'une carte via PUT
PUT http://localhost:3000/cards/
Content-Type: application/x-www-form-urlencoded

name=une carte neuve
&color=#F0F
&list_id=1

### supprimer une carte
DELETE http://localhost:3000/cards/2

### récuperer tous les tags
GET http://localhost:3000/tags

### création d'un tag
POST http://localhost:3000/tags
Content-Type: application/x-www-form-urlencoded

name=je suis le tag de test
&color=#F0F

### modification d'un tag
PATCH http://localhost:3000/tags/2
Content-Type: application/x-www-form-urlencoded

name=super important
&color=#F0F

### supprimer un tag
DELETE http://localhost:3000/tags/2

### associer une carte et un tag
POST http://localhost:3000/cards/1/tag
Content-Type: application/x-www-form-urlencoded

tag_id=3

### dissocier une carte et un tag
DELETE http://localhost:3000/cards/1/tag/3